modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/Mrbysco/Wooly-Trees/issues"
license="MIT"

[[mods]]
modId="woolytrees"
version="${file.jarVersion}"
displayName="Wooly Trees"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wooly-trees"
authors="ShyNieke, Mrbysco"
description='''
Trees that grow wool
'''
[[dependencies.woolytrees]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.5,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.woolytrees]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.5.14-beta,)"
ordering="NONE"
side="BOTH"